steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/npm-demo-app:$SHORT_SHA', '.' ]
- name: 'gcr.io/$PROJECT_ID/npm-jasmine-node'
  args: ['test']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/demo-app', 'demo-app=gcr.io/$PROJECT_ID/npm-demo-app:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=sdp-demo-cluster'
images:
- 'gcr.io/$PROJECT_ID/npm-demo-app'
tags:
- 'demo'
- 'nodejs'